### ISSUE TITLE
Peer indicated failure: Failure to initialize security context

### ISSUE THREAD

**Issue by VrushabhThosar** [joshelser/krb-thrift#1]
klist:
Ticket cache: FILE:/tmp/krb5cc_0
Default principal: root/admin@EXAMPLE.COM

Valid starting     Expires            Service principal
08/28/17 05:00:21  08/29/17 05:00:21  krbtgt/EXAMPLE.COM@EXAMPLE.COM
	renew until 08/28/17 05:00:21

Server: java -cp ${HADOOP_CONF_DIR}:${HADOOP_HOME}/share/hadoop/common/*:${HADOOP_HOME}/share/hadoop/common/lib/*:${HADOOP_HOME}/share/hadoop/hdfs/*:${HADOOP_HOME}/share/hadoop/hdfs/lib/*:krb-thrift-1.0-SNAPSHOT-jar-with-dependencies.jar joshelser.Server -p root/admin@EXAMPLE.COM -k root.keytab

Client: java -classpath /etc/hadoop/conf:/root/krb-thrift-1.0-SNAPSHOT-jar-with-dependencies.jar joshelser.Client -s 127.0.0.1 -p root -i admin

17/08/28 05:56:15 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/08/28 05:56:18 INFO joshelser.Client: Security is enabled: true
17/08/28 05:57:22 INFO joshelser.Client: Current user: root/admin@EXAMPLE.COM (auth:KERBEROS)
Exception in thread "main" org.apache.thrift.transport.TTransportException: Peer indicated failure: Failure to initialize security context
	at org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:190)
	at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:258)
	at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37)
	at joshelser.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:51)
	at joshelser.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:47)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at joshelser.TUGIAssumingTransport.open(TUGIAssumingTransport.java:47)
	at joshelser.Client.main(Client.java:94)

**Comment by joshelser** [comment]
And?

It's very unlikely that I'll devote any time to fixing up this repository as it was primarily a learning experience. If there's something obviously wrong with the code, I'd be happy to merge in a change from you to fix it.

If you're asking for basic debugging help, no. I won't be providing that.

**Comment by VrushabhThosar** [comment]
Ok.
Can you help me with its usage? Ijust want to know if my parameters are right

User: root
principal: root/admin@EXAMPLE.COM

Server:
java -cp ${HADOOP_CONF_DIR}:${HADOOP_HOME}/share/hadoop/common/*:${HADOOP_HOME}/share/hadoop/common/lib/*:${HADOOP_HOME}/share/hadoop/hdfs/*:${HADOOP_HOME}/share/hadoop/hdfs/lib/*:krb-thrift-1.0-SNAPSHOT-jar-with-dependencies.jar joshelser.Server -p root/admin@EXAMPLE.COM -k root_admin.keytab 

Client:
java -classpath /etc/hadoop/conf:krb-thrift-1.0-SNAPSHOT-jar-with-dependencies.jar joshelser.Client -s localhost -p root -i admin
